#!/bin/bash

munkipkg --create device-reassign-install

INSTALL_DIR=device-reassign-install
PAYLOAD_DIR=$PAYLOAD_DIR/payload/usr/local
mkdir -p $PAYLOAD_DIR

cp device-reassign $PAYLOAD_DIR/
sed -i '.plist' 's/com.github.munki/org.mirman/' $INSTALL_DIR/build-info.plist
sed -i '.plist' "s/<string>1.0/<string>$(cat version)/" $INSTALL_DIR/build-info.plist
munkipkg ./
cd ..
exit 0